# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy NodeJS Api to EC2 Instance (Self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, api-runner]

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Copy static folder before checkout
      run: cp -r /home/ubuntu/SpeedQuizz360/api/actions-runner/_work/SpeedQuizz_Api/SpeedQuizz_Api/public/ /home/ubuntu/video_images/
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Copy static folder after checkout
      run: cp -r /home/ubuntu/video_images/public/ /home/ubuntu/SpeedQuizz360/api/actions-runner/_work/SpeedQuizz_Api/SpeedQuizz_Api/
    - run: sudo pm2 restart api
